baseURL = "https://escalade-agen.fr/"
languageCode = "fr"
title = "Escalade Agen"
theme = "meghna"
SectionPagesMenu = "main"
googleAnalytics = "UA-55779894-1"
description = "Site d'actualité de l'escalade dans l'agenais."
preserveTaxonomyNames = true
disqusShortname = "escaladeAgen"
[permalinks]
  post = "/:title/"

[params]
  favicon = ""
  facebook = ""
  twitter = "https://twitter.com/sebmouret"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 6
  body_classes = "font"

